config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "kittens#index"

  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, presence: true
  validates :age, presence: true
  validates :cuteness, presence: true
  validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.json { render :json => @kittens }
    end
  end

  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.json { render :json => @kitten }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      flash[:success] = "Your kitten has been created!"
      redirect_to @kitten
    else
      flash.now[:error] = "The kitten couldn't be created, please fix your errors."
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @kitten = Kitten.find(params[:id])
  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      flash[:success] = "Your kitten has been updated!"
      redirect_to @kitten
    else
      flash.now[:error] = "The kitten couldn't be updated, please fix your errors."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    flash[:notice] = "Your kitten has been deleted."
    redirect_to root_path, status: :see_other
  end

  private
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_kitten_form.html.erb
<%= form_with model: kitten do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>
  <%= form.label :age %>
  <%= form.text_field :age %>
  <%= form.label :cuteness %>
  <%= form.text_field :cuteness %>
  <%= form.label :softness %>
  <%= form.text_field :softness %>
  <%= form.submit %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render "kitten_form", kitten: @kitten %>
<%= link_to "Delete", kitten_path(@kitten),
      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten %>
      <%= link_to "Delete", kitten_path(kitten),
            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
    </li>
  <% end %>
</ul>

<%= button_to "Create Kitten", new_kitten_path, method: "get" %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render "kitten_form", kitten: @kitten %>

app/views/kittens/show.html.erb
<h1><%= @kitten.name.capitalize %></h1>
<b>Age: </b><%= @kitten.age %>
<b>Cuteness: </b><%= @kitten.cuteness %>
<b>Softness: </b><%= @kitten.softness %>

<br><br><%= link_to "Edit", edit_kitten_path %>
<%= link_to "Delete", kitten_path(@kitten),
      data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <% flash.each do |name, message| %>
      <div class="<%= name %>"><%= message %></div>
    <% end %>
  </body>
</html>